version: "3.9"
services:
  db:
    image: postgres:14.8
    restart: unless-stopped
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    networks:
      - backend
  migrator:
    build:
      context: ./migrator
      dockerfile: Dockerfile
    environment:
      - PG_USER=${PG_USER}
      - PG_DATABASE=${PG_DATABASE}
      - PG_HOST=${PG_HOST}
    depends_on:
      - db
    networks:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DB_HOSTNAME=${PG_HOST}
      - DB_USERNAME=${PG_USER}
      - DB_NAME=${PG_DATABASE}
      - JWKS_ENDPOINT=${JWKS_ENDPOINT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8000:8000
    depends_on:
      migrator:
        condition: service_completed_successfully
    networks:
      - backend

networks:
  backend:
    driver: bridge
